### ISSUE TITLE
Unable to install xml-parser.

### ISSUE THREAD

**Issue by Mehulboghra** [thegreenter/greenter#104]
I need to install greenter/xml-parser ,but when I try it said that below

 Problem 1                                                                                                                 - greenter/xml-parser v1.2.2 requires greenter/core ^1.2 -> satisfiable by greenter/core[v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.3.0, v1.3.1, v1.3.2] but these conflict with your requirements or minimum-stability.                        - greenter/xml-parser v1.2.1 requires greenter/core ^1.2 -> satisfiable by greenter/core[v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.3.0, v1.3.1, v1.3.2] but these conflict with your requirements or minimum-stability.                        - greenter/xml-parser v1.2.0 requires greenter/core ^1.2 -> satisfiable by greenter/core[v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.3.0, v1.3.1, v1.3.2] but these conflict with your requirements or minimum-stability.                        - Installation request for greenter/xml-parser ^1.2 -> satisfiable by greenter/xml-parser[v1.2.0, v1.2.1, v1.2.2].       

How to resolve it?

**Comment by giansalex** [comment]
Hello @Mehulboghra, do you have other greenter/* dependency in your composer.json?
