### ISSUE TITLE
Anulacion boleta, sin nota de credito

### ISSUE THREAD

**Issue by jhuniors2111** [thegreenter/greenter#105]
Si todavia la boleta no ha sido enviada a la sunat por resumen diario y la quiero anular.. Tengo primero que enviar la boleta por resumen diario a la sunat y despues enviar otro resumen con la anulación.... Seria obligatori hacerle una nota fe credito con la anulación? O solo la anuló y listo aueda ahi???

**Comment by giansalex** [comment]
Hola, si para anular la boleta debes enviar 2 resumen diario, y no es necesario que se envíe nota de credito, ya que la boleta esta dada de baja.
