### ISSUE TITLE
GENERAR RESPUESTA DE LAS BOLETAS MEDIANTE RESUMENES DIARIOS

### ISSUE THREAD

**Issue by guillermosg28** [thegreenter/greenter#106]
Hola, envio resumenes diarios de boletas pero como hago para que me genere los CDR (R-20480657323-03-B001-27) por cada boleta ?
Muchas gracias de antemano.

**Comment by erajuan** [comment]
@guillermosg28  cuando envías por resumen diario las boletes y notas. 
Te devuelve un ticket, validas el ticket y obtienes el CDR del resumen diario. Este es valido para todas las boletas que enviaste en el resumen.

**Comment by guillermosg28** [comment]
@erajuan para dar de baja una boleta se puede hacer desde la opción DAR DE BAJA : 
Este es el código que hay de ejemplo pero no me funciona me sale error en el tipo de documento.
$detial1 = new VoidedDetail();
        $detial1->setTipoDoc('03')
            ->setSerie('B001')
            ->setCorrelativo('27')
            ->setDesMotivoBaja('Error en RUC');

**Comment by erajuan** [comment]
@guillermosg28 la comunicación de baja de boletas y notas (de boletas), se realiza en un resumen diario.
Tienes que enviar con estado **3**, Ten en cuenta que la boleta tiene que estar informado.
