### ISSUE TITLE
Sumatoria de IGV de operaciones gratuitas

### ISSUE THREAD

**Issue by erajuan** [thegreenter/greenter#108]
Cuando se tiene dos items 
- Grabada-Onerosa 
- Inafetacta-Gratuito
El mtoIGV incluye IGV de operaciones onerosas, y no corresponde al IGV de operaciones gratuitas ya que son montos distintos.

4311 - La sumatoria de los IGV de operaciones gratuitas de la línea (código tributo 9996) no corresponden al total 
```
{% if doc.mtoOperGratuitas %}
<cac:TaxSubtotal>
    <cbc:TaxableAmount currencyID="{{ doc.tipoMoneda }}">{{ doc.mtoOperGratuitas|n_format }}</cbc:TaxableAmount>
    <cbc:TaxAmount currencyID="{{ doc.tipoMoneda }}">{{ doc.mtoIGV|n_format }}</cbc:TaxAmount>
    <cac:TaxCategory>
        <cac:TaxScheme>
            <cbc:ID>9996</cbc:ID>
            <cbc:Name>GRA</cbc:Name>
            <cbc:TaxTypeCode>FRE</cbc:TaxTypeCode>
        </cac:TaxScheme>
    </cac:TaxCategory>
</cac:TaxSubtotal>
{% endif %}
```
Se puede agregar una nueva variable **mtoIGVGratuitas**?
- [x] Actualizar **core**
- [x] Actualizar **xml**
- [x] docs
- [x] demo

**Comment by giansalex** [comment]
Si seria una salida rápida, aunque aparentemente solo seria calcular la suma del detalle.

**Comment by erajuan** [comment]
...calcular la suma del detalle.
que greenter/xml se encargue de sumar los IGVs con filter?

**Comment by erajuan** [comment]
Es probable que el calculo sea necesario en el resumen diario. Aun no dice nada las guías

**Comment by giansalex** [comment]
Si esta bien, sería agregar ese campo.

**Comment by giansalex** [comment]
El cambio ya fue incluido en docs, demo.
