### ISSUE TITLE
ENVIAR DE NUEVO XML GENERADO

### ISSUE THREAD

**Issue by guillermosg28** [thegreenter/greenter#109]
Hola supongamos que no haya internet pero quiero realizar la venta, se genera el XML pero como envió de nuevo el XML a la SUNAT ? Gracias de antemano.

**Comment by giansalex** [comment]
Hola, existe un método para enviar solo el XML.
```php
$xml = file_get_contents('/xml-guardado/200000001-01-F001-1.xml');
$result = $see->sendXmlFile($xml);
````

**Comment by guillermosg28** [comment]
Tengo la versión 3.0 y no tengo esa función sendXmlFile.. a que se debe ?

**Comment by guillermosg28** [comment]
@giansalex tengo la versión 3.0 y no existe ese método sendXmlFile.. a que se debe ?

**Comment by giansalex** [comment]
Hola @guillermosg28, al parecer no se incluyo en ninguna versión, podrias utilizar el codigo que se realiza en esa función.

```php
        $xml = file_get_contents('/xml-guardado/200000001-01-F001-1.xml');

        $doc = new \DOMDocument();
        $doc->loadXML($xml);

        $reader = new \Greenter\Ws\Reader\XmlReader();
        $resolver = new \Greenter\Ws\Resolver\XmlTypeResolver($reader);
        $type = $resolver->getType($doc);

        $extractor = new \Greenter\Ws\Reader\XmlFilenameExtractor($reader);
        $name = $extractor->getFilename($doc);

        $result = $see->sendXml($type, $name, $xml);
```

**Comment by giansalex** [comment]
Hola @guillermosg28 , el método fue incluido en la versión `4.0`
