### ISSUE TITLE
Print Ticket Format

### ISSUE THREAD

**Issue by abelnexus** [thegreenter/greenter#115]
amigo para emitir tickets, es un documento diferente o solo es una factura con el aspecto diferente no hay en sunat informacion sobre tickets electronicos(para dar comprobantes con esas maquinas que imprimen tickets )

**Comment by yersey20037** [comment]
por favor podrias indicar el uso de la plantilla y donde se coloca?
gracias

**Comment by PSIONIC100** [comment]
> por favor podrias indicar el uso de la plantilla y donde se coloca? gracias

En tu proyecto crea una directorio (puedes llamarlo templates), dentro creas las plantillas que gustes con twig (debe terminar en html.twig) luego haces lo siguiente:
`
$customDirectory =  '/templates';
$report = new HtmlReport($customDirectory );
$report->setTemplate('custom_ticket.html.twig');
 `
Eso es todo.
