### ISSUE TITLE
Anulacion de Nota de Credito

### ISSUE THREAD

**Issue by jhuniors2111** [thegreenter/greenter#130]
Buenas , si por algún motivo hacen una nota de crédito de una factura y  no era para esa factura, se puede anular
Ejemplo :
FB01-1 tenian que anular
FB01-2 pero anularon esta factura

ahora la nota de crédito se hizo  a la FB01-1, se podrá anular esa nota de crédito?, o ya se tiene que hacer otra factura y anular la factura que si corresponde que es la FB01-2, o hay otra solución mas factible.

**Comment by giansalex** [comment]
Si, se podría anular la nota de crédito con una [Comunicacion de baja](https://github.com/thegreenter/demo/blob/master/examples/comunicacion-baja.php#L20), y emitir otra nota de crédito con otro correlativo.
