### ISSUE TITLE
ERROR AL GENERAR ZIP

### ISSUE THREAD

**Issue by guillermosg28** [thegreenter/greenter#131]
Hola, me sale este error: tempnam(): file created in the system's temporary directory
PHP 7.2 (Xamp)
SO: macOS Catalina

**Comment by giansalex** [comment]
Hola @guillermosg28 , eso no debería generar un error, ya que es un `warning`, podrías revisar si tienes definida una ruta en `upload_tmp_dir ` dentro de `php.ini`.

**Comment by giansalex** [comment]
Anteriormente no se necesitaba guardar zip temporalmente, pero la implementación no funcionó en todos los casos, y se volvió a usar `ZipArchive` incluida en la extension `zip` que requiere leer el archivo en disco.  Pero ahora he encontrado una implementación de zip que evitaria eso [nelexa/zip](https://github.com/Ne-Lexa/php-zip) , podría estar incluida en un siguiente versión.

**Comment by giansalex** [comment]
Este issue se mantendrá abierto, para tener en cuenta la inclusión de `nelexa/zip`  u otro similar en la compresión/decompresión de archivos en memoria.
