### ISSUE TITLE
doc.descuentos invoice2.1.xml.twig

### ISSUE THREAD

**Issue by thefantas** [thegreenter/greenter#133]
Hola, 
Analizando[ invoice2.1.xml.twig, en la línea 252 ](https://github.com/thegreenter/xml/blob/fcecc85a5877a14fa10cf8eb6010e62cccbdae6d/src/Xml/Templates/invoice2.1.xml.twig#L252) y AjustesValidacionesCPEv20200529.xlsx Fila 381, indica que son cargos y descuentos globales, lo mismo que el xml (descuento global porque es doc.descuentos).

Revisando los ejemplos, no encontré ninguno que lo aplique... a lo que asúmo que sería similar al ejemplo que hay en details pero aplicado al global del invoice.

```
$invoice
		->setDescuentos([
					(new Charge())
					->setCodTipo('00')
					->setFactor(0.30)
					->setMontoBase(100)
					->setMonto(30)
				])
```

Saludos.

**Comment by thefantas** [comment]
```
	->setSumDsctoGlobal()
	->setMtoDescuentos()
```
Adicionalmente, estos 2 items no los encuentro en las plantillas, están en desuso? :)

**Comment by giansalex** [comment]
Hola, si son cargos y descuentos, se incluyen en `setCargos`  y `setDescuentos`.

![image](https://user-images.githubusercontent.com/14926587/90321756-3af8a300-df12-11ea-8b38-932b9a280fba.png)

Los últimos campos que mencionas se usaban en la versión anterior UBL 2.0

**Comment by thefantas** [comment]
Hola, entonces la forma en la que aplico $invoice->SetDescuentos... es correcto? como dije no vi ningún ejemplo (al invoice no al details).

Saludos.

**Comment by giansalex** [comment]
Si, este es el [ejemplo](https://github.com/thegreenter/demo/blob/master/examples/factura-descuento-global.php#L29) que incluye descuento global `$invoice->setDescuentos()`
