### ISSUE TITLE
Sunat warning message cuando mando un "Total descuentos"

### ISSUE THREAD

**Issue by nooss** [thegreenter/greenter#137]
Tengo una factura con 3 lineas de producto ; cada una tiene un descuento de 10%.
Entiendo que hay que indicar a la sunat el "Total descuento" de la factura, para eso yo uso :
$invoice = new Invoice();
$invoice->setMtoDescuentos(4.24)
...

El XML que mando a la SUNAT esta en el siguiente file : 
[invoice.txt](https://github.com/thegreenter/greenter/files/5105101/invoice.txt)

Pero la SUNAT me respondo este mensage :
Notes: 4307 - La sumatoria consignados en descuentos globales no corresponden al total. - INFO : 4307 (nodo: "cac:LegalMonetaryTotal/cbc:AllowanceTotalAmount" valor: "4.24")

Ayuda por favor

**Comment by giansalex** [comment]
Hola, [este es un ejemplo](https://github.com/thegreenter/demo/blob/master/examples/factura-descuento-linea.php) de descuento por linea que afecta a la base imponible, `MtoDescuentos` solo SUNAT lo necesita para la suma de descuentos que no afectan la base imponible.

_Referencia_:
![image](https://user-images.githubusercontent.com/14926587/90821685-e893f980-e2f8-11ea-9cf2-197c84c5b22a.png)

**Comment by nooss** [comment]
> Hola, [este es un ejemplo](https://github.com/thegreenter/demo/blob/master/examples/factura-descuento-linea.php) de descuento por linea que afecta a la base imponible, `MtoDescuentos` solo SUNAT lo necesita para la suma de descuentos que no afectan la base imponible.
> 
> _Referencia_:
> ![image](https://user-images.githubusercontent.com/14926587/90821685-e893f980-e2f8-11ea-9cf2-197c84c5b22a.png)


Gracias Giansalex, me ayudo mucho !!

**Comment by nooss** [comment]
Gracias Giansalex, me ayudo mucho !!
