### ISSUE TITLE
Monto total de tributos

### ISSUE THREAD

**Issue by thefantas** [thegreenter/greenter#139]
Monto total de tributos:

Si el Tag UBL existe, el valor del Tag UBL es diferente de la sumatoria de '**Monto de la sumatoria**' (cbc:TaxAmount) de los  tributos '1000', '1016', '2000', '7152' y '9999',  con una tolerancia + - 1.

Pero, según el código de abajo solo procesa el tributo 1000, 2000 y 9999.

Saludos.

https://github.com/thegreenter/greenter/blob/50726ca0ea46f9af3aec42f0611de2f064a901ea/packages/xml-parser/src/Xml/Parser/InvoiceParser.php#L155-L173

**Comment by giansalex** [comment]
Hola @thefantas, ese paquete `greenter/xml-parser` se quedó un poco atrás en la versión UBL 2.0, como indica la [lista de documentos soportados](https://github.com/thegreenter/xml-parser/tree/2.0#documentos-soportados), igual sigue siendo util para comprobantes mas antiguos, para UBL 2.1 se necesitaría crear nuevas implementaciones y puede tenerse como base el codigo que muestras.

**Comment by thefantas** [comment]
Sigo encontrando más imprecisiones con respecto al XLSX (ajustes de validación), pero antes de mencionarlos, este xml-parser es el que actualmente genera el xml UBL 2.1 que se usa en factura, boleta.. etc.?

**Comment by giansalex** [comment]
No, `xml-parser` es una herramienta aparte que no forma parte del flujo principal de facturación electrónica, pero puede ser útil en casos cuando una empresa recibe comprobantes electrónicos emitido por terceros, y quiere extraer datos de dichos comprobantes (xml).

Los XML ubl 2.1 se generan en `greenter/xml`
