### ISSUE TITLE
GENERAR NOTA DE CREDITOS A UNA BOLETA YA EMITIDA

### ISSUE THREAD

**Issue by guillermosg28** [thegreenter/greenter#140]
Hola como puedo generar una nota de credito a una boleta ya emitida ? Gracias de antemano.

**Comment by thefantas** [comment]
https://github.com/thegreenter/demo/blob/master/examples/nota-credito.php
Solo pon los parámetros para generar tu "BC01-00000001", recuerda que tanto boletas como sus notas de crédito o débito se envían como resumen. 

Saludos.

**Comment by giansalex** [comment]
Se incluyó un ejemplo de NCR en [nota-credito-boleta.php](https://github.com/thegreenter/demo/blob/b9e9c9ad901653992003bdb321b82e191ccefec8/examples/nota-credito-boleta.php),  acerca del envío a SUNAT, según esta [resolución art. 12](http://www.sunat.gob.pe/legislacion/superin/2019/114-2019.pdf), no es necesariamente obligatorio enviarlo por resumen diario, podría enviarse individualmente como se hace con facturas, pero tener en cuenta que no debe superar los 5 días después de la emisión.
