### ISSUE TITLE
Cambiar nombre igv por uno general.

### ISSUE THREAD

**Issue by thefantas** [thegreenter/greenter#141]
https://github.com/thegreenter/greenter/blob/b9225c3643ca5288d882101138a507f1f0625794/packages/xml/src/Xml/Templates/invoice2.1.xml.twig#L468-L481

Creo que deberíamos cambiar el nombre "igv" por "impuesto" porque esa misma variable puede ir el ivap, u otro tributo.

**Comment by giansalex** [comment]
Se uso el mismo campo porque en el excel de validaciones se ubica dentro el catalogo de Tipos de Afectación de IGV (17), y no se manejo como ISC, ICBPER y OTROS, que se manejan en campos serados.
Tendré en cuenta agregar un ejemplo de IVAP en `greenter/demo` .

**Comment by giansalex** [comment]
Se agregó el ejemplo de IVAP https://github.com/thegreenter/demo/pull/94
