### ISSUE TITLE
StatusResult Content "" Result 0

### ISSUE THREAD

**Issue by thefantas** [thegreenter/greenter#142]
https://github.com/thegreenter/greenter/blob/fa3728baca8bfce623661fbfbcb33d2b0189dc30/packages/ws/src/Ws/Services/ExtService.php#L68-L75

En algunos casos la SUNAT responde con lo siguiente al realizar una consulta de un ticket (getStatus).

```
object(Greenter\Model\Response\StatusResult)[12]
  protected 'code' => string '0' (length=1)
  protected 'cdrZip' => null
  protected 'cdrResponse' => null
  protected 'success' => boolean false
  protected 'error' => null
```

Pero el único filtro de la función getstatusinternal es..

 ```
       if (!isset($response->status)) {
            throw new Exception('Invalid getStatus service response.');
```

Si existe $response->status -> está definida y no es NULL continúa; hasta aquí está bien, pero ocurre que a veces content devuelve vacío y luego cuando procesa el contenido zip produce un error.

```
          $result
                ->setSuccess(true)
                ->setCdrResponse($this->extractResponse($cdrZip))
                ->setCdrZip($cdrZip);
```

Personalmente le puse " if ($this->isProcessed($code) && !empty($cdrZip)) { ... } ".
Ahora la pregunta es: ¿Cuál es más importante para interpretar la respuesta?, ¿Qué tenga el código sea "0" y/o que contenga un CDR. 

Pd. En este caso el documento fue aceptado por SUNAT (era un RA), pero la consulta de ticket no devuelve CDR.

Saludos.

**Comment by giansalex** [comment]
El código se hizo siguiendo los manuales de SUNAT, pero si se ha dado el caso que mencionas, de todas formas debería agregarse la validación y lanzar una excepción.

**Comment by thefantas** [comment]
¿Cuál es más importante para interpretar la respuesta?, ¿Qué tenga el
código sea "0" y/o que contenga un CDR.?
