### ISSUE TITLE
DOMDocument::loadXML(): Empty string supplied as input

### ISSUE THREAD

**Issue by alexsoft12** [thegreenter/greenter#147]
Necesito su orientacion para reparar este error
al parecer se envia el comprobante pero la sunat no devuelve el cdr 

File: /.../.../../greenter/ws/src/Ws/Reader/XmlReader.php
 Line: 58 
Message: DOMDocument::loadXML(): Empty string supplied as input

**Comment by giansalex** [comment]
Hola @alexsoft12 , se incluirá en una siguiente versión, esto es algo recurrente?

**Comment by alexsoft12** [comment]
Hola @giansalex  gracias por tu respuesta, tengo implementado en laravel  y uso beginTransaction  cuando  se genera un error 
hace un rollback pero el comprobante ya fue enviado  y no llega actulizar por el error y en mi tabla se registra como que nunnca se envio, los clientes intentan enviar y resulta que en sunat ya existe 

Ejemplo 

```
 try {
   $sunat = new Sunat();
     DB::beginTransaction();
        // transacion en BD
      
   $input = $request->all();
   $order = Order::create($input);

    DB::commit();

   $respuesta = $sunat->sendComprobante($order);

   $estado = Order::find($order->id);
   $estado->estado_sunat = $respuesta['code'];
   $estado->description = $respuesta['description'];
   $estado->save();

 } catch (\Exception $e) {
          DB::rollBack();
       \Log::emergency("File:" . $e->getFile(). "Line:" . $e->getLine(). "Message:" . $e->getMessage());
}

```
Gracias  de vervdad  esperare la actualizacion si llego corregir  temporalmente les are saber 👍 💯

**Comment by giansalex** [comment]
Que no devuelva el CDR, rompe el flujo y seria un error de SUNAT, pensaba incluir un tipo excepción personalizado, o tambien se puede consultar el CDR con `ConsultService::getStatusCdr`.

**Comment by giansalex** [comment]
Ahora se retornara un error, en vez de esa excepción. En general se puede dar el caso de que el comprobante ya fue previamente enviado, sea porque SUNAT no devolvio el CDR o se envío por otro medio. Para ello se puede tener en cuenta estos codigos de error:

|Code  |Description|
|-|-|
|1032|El comprobante ya esta informado y se encuentra con estado anulado o rechazado|
|2282|Existe documento ya informado anteriormente|
