### ISSUE TITLE
Al emitir nota de Credito de boleta me sale el error en la Sunat del 1079

### ISSUE THREAD

**Issue by jhuniors2111** [thegreenter/greenter#154]
A que se debe que salga ese error en la sunat,Gracias

**Comment by giansalex** [comment]
Hola @jhuniors2111 , en este [link](https://cpe.sunat.gob.pe/node/88#item-1) puedes encontrar un excel(Reglas de Validación) con esos códigos de error segun el comprobante.
![image](https://user-images.githubusercontent.com/14926587/103155471-62883380-476e-11eb-9707-95461395bea5.png)
Tendrías que enviarlo en un resumen diario.
