### ISSUE TITLE
Versión 4.2 de dependencia de greenter/xml-parser no existe

### ISSUE THREAD

**Issue by barclaymichael** [thegreenter/greenter#156]
greenter/xml-parser depende de grenter/core version ^4.2, sin embargo la última versión de release es 4.1. Existe además la versión pre-release 4.2.x-dev (con alias dev-master). Estuve probando el paquete usando la versión de pre release:

"require": {
....
        "greenter/core": "dev-master", 
}

No he tenido problemas, pero no estoy familiarizado con el código como para saber si sería más recomendable bajar a la 4.1.

Links relevantes:
greenter/core en packagist: https://packagist.org/packages/greenter/core

**Comment by giansalex** [comment]
Hola @barclaymichael, la version 4.1 es la ultima, puedes usar esa.

**Comment by barclaymichael** [comment]
Oka, me quedo en la 4.1 de ambos.

**Comment by giansalex** [comment]
@barclaymichael si necesitas trabajar con `dev-master`, necesitas incluir en composer.json
```json
{
   "minimum-stability": "dev",
}
```

**Comment by barclaymichael** [comment]
Perfecto, gracias.
