### ISSUE TITLE
Obtener el codigo hash

### ISSUE THREAD

**Issue by jsponceA** [thegreenter/greenter#157]
Disculpen soy nuevo en esto de la facturacion y quisiera saber como obtener el codigo hash del cdr

**Comment by giansalex** [comment]
Hola @jsponceA, aqui hay un ejemplo para obtener el hash
```php
$xml = '<Invoice ....>';
 // otro ejem:  $xml = file_get_contents('2000000001-01-F001-1.xml');
$hash = (new Greenter\Report\XmlUtils())->getHashSign($xml);


```

**Comment by jsponceA** [comment]
@giansalex  estaa clase XmlUtils esta dentro de la libreria de grender o la tengo que descargar por aparte, lo digo ya que no me reconoce?
-Encontra una solución rápida y simple espero que alguien le pueda servir.

**Comment by giansalex** [comment]
@jsponceA estaba aquí: `greenter/report`
