### ISSUE TITLE
No tiene el perfil para enviar comprobantes electrónicos

### ISSUE THREAD

**Issue by guillermosg28** [thegreenter/greenter#158]
Hola alguien me ayuda llevo 2 dias con este error, ya cree 2 veces usuarios secundarios, le he asignado todos los permisos.

message: "No tiene el perfil para enviar comprobantes electrónicos - Detalle: Rejected by policy."

**Comment by alexsoft12** [comment]
Hola revisa bien y espera a veces tarda hasta 24  horas .

**Comment by guillermosg28** [comment]
> Hola revisa bien y espera a veces tarda hasta 24  horas .

Ya han pasado 48 horas 🙁

**Comment by alexsoft12** [comment]
Entonces no le has dado permisos adecuados en el portal de la sunat

**Comment by guillermosg28** [comment]
> Entonces no le has dado permisos adecuados en el portal de la sunat

Le he dado permisos como siempre, a otras empresas le he hecho lo mismo y normal.

**Comment by alexsoft12** [comment]
probaste con usuario princiapal ?

**Comment by guillermosg28** [comment]
> probaste con usuario princiapal ?

Acabo de probar y me sale lo mismo.

**Comment by giansalex** [comment]
Hola @guillermosg28 , puedes revisar que los datos se han configurados correctamente, o de lo contrario comunicarte con sunat.
```
usuario = RUC + Usuario SOL
clave    = contraseña SOL
```
