### ISSUE TITLE
Se debe especificar DateTimeZone (Error 2346)

### ISSUE THREAD

**Issue by Arturor72** [thegreenter/greenter#159]
Al realizar envíos a SUNAT en producción en comunicación de baja hemos tenido problemas, en el xml la fecha de emisión se coloca con un día anterior; dando como código de respuesta 2346.

En la demo también se puede ver el mismo problema.
https://greenter-sample.herokuapp.com/

**Comment by Arturor72** [comment]
Se soluciono especificando el DateTimeZone, en los campos fecha no solo de comunicación de baja, sino también en la emisión de facturas, boletas, notas de crédito y resúmenes diarios, en el caso de Lima se debe especificar de la siguiente manera:

`setFechaEmision(new DateTime($invoiceLocal->fechaEmision, new DateTimeZone('America/Lima')))`

**Comment by giansalex** [comment]
Hola @Arturor72 , habia una bug para el caso resumen diario, c. de baja, ya que la fecha del archivo lo enviaba con la zona horaria del servidor, en vez de Lima.
Para los otros comprobantes, si tu sistema maneja las fechas con la misma zona horaria que tu servidor no habría problema, en todo caso para evitar este inconveniente, deberías incluir la zona horaria, como el ejemplo que colocas o de esta forma:
```php
new DateTime('2021-02-03 08:30:00-05:00'); // America/Lima
new DateTime('2021-02-04 01:30:00+00:00'); // UTC
```
