### ISSUE TITLE
Soporte para PHP 8

### ISSUE THREAD

**Issue by willyk** [thegreenter/greenter#163]
Estimados, estamos tratando de usar la librería en la versión 4.2 con PHP 8.0 y nos da el siguiente error:

Problem 1
    - nelexa/zip[3.3.0-alpha1, ..., 3.3.3] require php ^5.5.9 || ^7.0 -> your php version (8.0.2) does not satisfy that requirement.
    - greenter/greenter 4.2.0 requires nelexa/zip ^3.3 -> satisfiable by nelexa/zip[3.3.0-alpha1, ..., 3.3.3].
    - Root composer.json requires greenter/greenter ^4.2 -> satisfiable by greenter/greenter[4.2.0].

Por favor nos pueden comentar si hay algo a configurar para trabajar con PHP 8.0

Gracias por su respuesta.

**Comment by giansalex** [comment]
Hola @willyk , `greenter/greenter` como tal soporta PHP 8, pero hay una dependencia que aun no ha actualizado la restricción de PHP 7, para tal caso podrías instalarlo ignorar la version de php.

```bash
 composer require greenter/greenter --ignore-platform-req=php
```

**Comment by willyk** [comment]
Gracias, buen dato para ejecutarlo desde el comando. Es posible configurarlo desde composer.json con esa regla para que solo aplique para greenter/greenter ?

**Comment by giansalex** [comment]
Si no usas características de lenguaje propias de PHP 8, podría configurarse en composer.json 
```json
 "config": {
        "platform": {
            "php": "7.4"
        }
    }
```

De lo contrario se tendría que excluir la versión de PHP en el siguiente comando:
```bash
composer install --ignore-platform-req=php
```
