### ISSUE TITLE
ERROR unsupported zip format

### ISSUE THREAD

**Issue by guillermosg28** [thegreenter/greenter#164]
Hola me sale este error, **message: "0156 Error: Invalid or unsupported zip format. No END header found"**
Tengo php 7.3
Version de greenter: 4.2

**Comment by giansalex** [comment]
@guillermosg28 hola, esto ocurre de forma permanente?

**Comment by guillermosg28** [comment]
@giansalex  no me deja emitir ningunaFACTURA  :/

**Comment by giansalex** [comment]
@guillermosg28 has intentado desde otra computadora, y si eso ocurre tambien en Beta?
