### ISSUE TITLE
Obtener CDR de OSE-EFACT

### ISSUE THREAD

**Issue by willianmzc** [thegreenter/greenter#167]
https://github.com/thegreenter/greenter/blob/5c2890a7495d90c7c28f4b9849ed5f2c45d79fde/packages/ws/src/Ws/Reader/DomCdrReader.php#L57

      ` $nodePrefix = 'ns3:DocumentResponse/ns3:Response/';
        $cdr = new CdrResponse();
        $cdr->setId($this->reader->getValue($nodePrefix.'ReferenceID'))
            ->setCode($this->reader->getValue($nodePrefix.'ResponseCode'))
            ->setDescription($this->reader->getValue($nodePrefix.'Description'))
            ->setNotes($this->getNotes());
        return $cdr; `

**Comment by giansalex** [comment]
@willianmzc Hola, podrías proveer un ejemplo del  CDR - xml

**Comment by willianmzc** [comment]
[efact_cdr1.zip](https://github.com/thegreenter/greenter/files/6168363/efact_cdr1.zip)

**Comment by giansalex** [comment]
@willianmzc la corrección esta en la ultima version [v4.3.1](https://github.com/thegreenter/greenter/releases/tag/v4.3.1)

**Comment by willianmzc** [comment]
Gracias @giansalex
