### ISSUE TITLE
Guia de remision : Al enviar devuelve error 0151 de nombre de archivo zip incorrecto

### ISSUE THREAD

**Issue by sysarp** [thegreenter/greenter#169]
Descripcion: Error 0151 
20000000005 | EMPRESA SAC | 
El nombre del archivo ZIP es incorrecto - Detalle: xxx.xxx.xxx value='ticket:  error: 
Error de nombre archivo "20000000005-09-T001-00000001.zip codigo cpe: 09" no es un cpe valido' 

// https://e-beta.sunat.gob.pe/ol-ti-itemision-guia-gem-beta/billService 
// https://e-guiaremision.sunat.gob.pe/ol-ti-itemision-guia-gem/billService

A alguien le pasa lo mismo? alguna sugerencia?

El archivo XML 20000000005-09-T001-00000001.xml

**Comment by giansalex** [comment]
@sysarp estas probando en beta?, porque en el demo desplegado no ocurre, [guia-remision-demo](https://greenter-sample.herokuapp.com/?doc=examples/guia-remision.php)

**Comment by sysarp** [comment]
En ambos me pasa esto ya lo probe con un ruc valido estoy con la version greenter/greenter": "^3.0

**Comment by sysarp** [comment]
tengo esto agregado en blanco 

<cac:SellerSupplierParty>
<cbc:CustomerAssignedAccountID schemeID=""/>
<cac:Party>
<cac:PartyLegalEntity>
<cbc:RegistrationName></cbc:RegistrationName>
</cac:PartyLegalEntity>
</cac:Party>
</cac:SellerSupplierParty>

Lo retire y ahora ya lo probe con SOAP UI ya pasa pero algo mas tengo en la app que sigue saliendo el mismo error, seguire revisando

**Comment by sysarp** [comment]
tengo resultado con esto con el ejemplo:

object(Greenter\Model\Response\Error)#451 (2) { ["code":protected]=> string(4) "0151" ["message":protected]=> string(175) "El nombre del archivo ZIP es incorrecto - Detalle: xxx.xxx.xxx value='ticket: error: Error de nombre archivo "20123456789-09-T001-123.zip codigo cpe: 09" no es un cpe valido'" }


		$rel = new Document();
		$rel->setTipoDoc('02') // Tipo: Numero de Orden de Entrega
		->setNroDoc('213123');

		$transp = new Transportist();
		$transp->setTipoDoc('6')
		    ->setNumDoc('20000000002')
		    ->setRznSocial('TRANSPORTES S.A.C')
		    ->setPlaca('ABI-453')
		    ->setChoferTipoDoc('1')
		    ->setChoferDoc('40003344');

		$envio = new Shipment();
		$envio
		    ->setCodTraslado('01') // Cat.20
		    ->setDesTraslado('VENTA')
		    ->setModTraslado('01') // Cat.18
		    ->setFecTraslado(new DateTime())
		    ->setCodPuerto('123')
		    ->setIndTransbordo(false)
		    ->setPesoTotal(12.5)
		    ->setUndPesoTotal('KGM')
		//    ->setNumBultos(2) // Solo válido para importaciones
		    ->setNumContenedor('XD-2232')
		    ->setLlegada(new Direction('150101', 'AV LIMA'))
		    ->setPartida(new Direction('150203', 'AV ITALIA'))
		    ->setTransportista($transp);

		$despatch = new Despatch();
		$despatch->setTipoDoc('09')
		    ->setSerie('T001')
		    ->setCorrelativo('123')
		    ->setFechaEmision(new DateTime())
		    ->setCompany($util->shared->getCompany())
		    ->setDestinatario((new Client())
		        ->setTipoDoc('6')
		        ->setNumDoc('20000000002')
		        ->setRznSocial('EMPRESA ( />) 1'))
		    ->setTercero((new Client())
		        ->setTipoDoc('6')
		        ->setNumDoc('20000000003')
		        ->setRznSocial('EMPRESA SA'))
		    ->setObservacion('NOTA GUIA')
		    ->setRelDoc($rel)
		    ->setEnvio($envio);

		$detail = new DespatchDetail();
		$detail->setCantidad(2)
		    ->setUnidad('ZZ')
		    ->setDescripcion('PROD 1')
		    ->setCodigo('PROD1')
		    ->setCodProdSunat('P001');

		$despatch->setDetails([$detail]);


		// Envio a SUNAT.
		$see = $util->getSee(SunatEndpoints::GUIA_BETA);

		$res = $see->send($despatch);
		$util->writeXml($despatch, $see->getFactory()->getLastXml());

		if ($res->isSuccess()) {
			//@var $res \Greenter\Model\Response\BillResult
			$cdr = $res->getCdrResponse();
			$util->writeCdr($despatch, $res->getCdrZip());

			echo $util->getResponseFromCdr($cdr);
		} else {
			var_dump($res->getError());
		}
die("ok");



alguna sugerencia??

**Comment by giansalex** [comment]
@sysarp has intentado ejecutarlo directamente desde el proyecto [demo](https://github.com/thegreenter/demo), por que tanto en el desplegado en [heroku](https://greenter-sample.herokuapp.com/?doc=examples/guia-remision.php) y en local funcionan sin problema.

**Comment by sysarp** [comment]
Una libreria mal invocada la de Guia por Invoice

use Greenter\Model\Company\Company;
use Greenter\Model\Company\Address;
use Greenter\Model\Client\Client;
use Greenter\Model\Despatch\Despatch;
use Greenter\Model\Despatch\DespatchDetail;
use Greenter\Model\Despatch\Direction;
use Greenter\Model\Despatch\Shipment;
use Greenter\Model\Despatch\Transportist;
use Greenter\Model\Response\BillResult;
use Greenter\Model\Sale\Document;
use Greenter\Ws\Services\SunatEndpoints;
**use Nomade\v5\Sunat\greenter\src\UtilGuide;**//use Nomade\v5\Sunat\greenter\src\Util;

**Comment by sysarp** [comment]
Ya quedo en modo demo ahora a probar en produccion.
Gracias por la atencion.
