### ISSUE TITLE
Error al emitir facturas

### ISSUE THREAD

**Issue by AnthonyLJ96** [thegreenter/greenter#170]
Hola @giansalex estoy teniendo un error intentar emitir facturas, al parecer es cuando intenta firmar el XML, aquí dejo el detalle del error, esto empezó a suceder sin haber hecho ningún cambio.

File:
vendor/greenter/xmldsig/src/XMLSecurityKey.php
Line:
502
Message:
Failure Signing Data: error:04088003:rsa routines:RSA_setup_blinding:BN lib - 1

**Comment by giansalex** [comment]
@AnthonyLJ96 Hola, tal vez hay problema con el formato del certificado, lo convertiste como en este [ejemplo](https://github.com/thegreenter/xmldsig/blob/master/CONVERT.md#convert-to-pem)?.

**Comment by AnthonyLJ96** [comment]
@giansalex , si exactamente, antes se podía emitir con normalidad y ahora da ese error, para asegurarme volví a convertir el certificado pero da el mismo error.

**Comment by giansalex** [comment]
@AnthonyLJ96 si no actualizaste la libreria, no debería haber cambiado eso.
En todo caso, actualizar a la ultima version

**Comment by AnthonyLJ96** [comment]
@giansalex tema cerrado, había sido un tema de servidor.
