### ISSUE TITLE
Error al genear xml

### ISSUE THREAD

**Issue by stoner6593** [thegreenter/greenter#171]
Parse error: syntax error, unexpected 'ZipContainer' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in C:\laragon\www\quadrum\vendor\nelexa\zip\src\ZipFile.php on line 64

**Comment by giansalex** [comment]
@stoner6593 Hola, usas la misma versión de PHP cuando instalaste los paquetes?, que versión de PHP utilizas

**Comment by stoner6593** [comment]
@giansalex Estoy usando la versión 7.3.27 de php, tengo mas versiones instaladas, pero con ésta hice todas las instalaciones de las dependencias.
 Según lo que indica tu repo hay que instalar zlib pero no encuentro esa librería, alguna sugerencia?

**Comment by giansalex** [comment]
El problema parece ser que se esta utilizando una versión del paquete `nelexa/zip` que solo funciona con PHP 7.4 o 8.x

**Comment by stoner6593** [comment]
O sea obligatoriamente debo migrar a una de esas versiones? alguna otra alternativa?

**Comment by giansalex** [comment]
Puedes ejecutar `composer info`, y deberia estar la version:
```
# composer info
nelexa/zip  3.3.3  PhpZip is .....
```
si no aparece esa version, deberías volver instalarlo pero con php `7.3` directamente:
```
/path/7.3/php composer.phar require greenter/lite
```

**Comment by giansalex** [comment]
Los datos deben estar mal calculados, puedes ver ejemplos [aqui](https://github.com/thegreenter/demo)

**Comment by stoner6593** [comment]
Solucionado, error de cálculos.
