### ISSUE TITLE
OSE - Obligatorio?

### ISSUE THREAD

**Issue by OD-n** [thegreenter/greenter#172]
Buenos días, quisiera preguntar si es necesario contratar una OSE para el envío de comprobantes electrónicos, tomé una captura donde aparecen los requisitos para ser emisor electrónico y requerimiento aparece validar o autorizar un OSE
![image](https://user-images.githubusercontent.com/28074529/120693287-726b1880-c46e-11eb-987b-6496ad10b762.png)

si alguien sabe de una guía para configurar y ser emisor electrónico les agradezco si pudieran darme información, muchas gracias.
Cabe resaltar que ya tengo el certificado subido al portal en SUNAT, ahora mismo tengo el error de **"No tiene el perfil para enviar comprobanteselectrónicos"**  y no sé si sea por eso, muchas gracias

**Comment by erajuan** [comment]
1) Si no estas obligado a usar OSE - puedes seguir enviando tus comprobantes a sunat.
2) Para ser emisor electrónico no necesitas configurar nada.
3) No tiene perfil: Crear usuario secundario y darle los permisos (esperar 8horas aprox ó más)

**Comment by OD-n** [comment]
Muchas gracias, esperaré un poco para ver que no haya problemas, te lo agradezco
