### ISSUE TITLE
Guia de Remision: Falta Tag <cac:Signature> en XML

### ISSUE THREAD

**Issue by dlopez525** [thegreenter/greenter#173]
Falta tag `<cac:Signature>` en XML de Guias de Remision. 

Genera respuesta con error 2076.

Respuesta de Error **"2076 | {\"message\":\"cac:Signature\\/cbc:ID - Falta el identificador de la firma | Signature ID is null \"}"**

**Comment by Recursero** [comment]
Hola Giancarlos:

Estaba revisando la versión que uso de Lycet y me he percatado que a pesar que hago el clone de la última versión, no se actualiza despatch.xml.twig con esta última modificación. ¿Estaré olvidando ejecutar algún comando? Gracias de antemano por tu respuesta.

**Comment by giansalex** [comment]
Eliminar la carpeta `/var`

**Comment by Recursero** [comment]
Hola Giancarlos:

No subo la carpeta var/ y tampoco está presente en tiempo de ejecución.
![image](https://user-images.githubusercontent.com/45543343/163229938-45fdf604-335d-4398-b05d-e04b98d4a12a.png)
¿Podrá ser otra cosa que esté faltando?

**Comment by Recursero** [comment]
Veo que en las dependencias declaradas en composer de Lycet hace referencia a greenter/lite pero veo esta versión:
![image](https://user-images.githubusercontent.com/45543343/163231482-c47dc67b-d114-4526-a36f-287c1ca85f5b.png)

**Comment by Recursero** [comment]
Hola Giancarlos,

Pudiste revisar este caso?

**Comment by giansalex** [comment]
@Recursero lycet necesita actualizar a la ultima version de greenter, podrias ejecutar este comando
```
composer update 
```
y enviar un pull request a Lycet seria de gran apoyo.
