### ISSUE TITLE
Consulta CDR

### ISSUE THREAD

**Issue by stoner6593** [thegreenter/greenter#176]
Hola amigo, existe algún método para consultar el CDR y estado del comprobante enviado?
resulta que existen ocasiones en las que realizo el envío pero no me retorna CDR, entonces
estoy implementando una opción para poder obtenerlo.

**Comment by giansalex** [comment]
@stoner6593 Hola, si, esta es la guia https://greenter.dev/packages/ws/#consulta-cdr
