### ISSUE TITLE
Guia de remision

### ISSUE THREAD

**Issue by guillermosg28** [thegreenter/greenter#177]
Hola buenas noches estoy generando una Guía de remisión transportista y me genera este error.
$guiaRemision = (new Document())
                ->setTipoDoc(31) // Codigo de doc. relacionado, Catalogo 01
                ->setNroDoc('EG01-15'); // Serie y correlativo de la guia de remision

///ERROR
"4009 - El DocumentTypeCode de Otros documentos relacionados tiene valores incorrectos. - Documento Relacionado : 31-EG01-15: 4009 (nodo: \"cac:AdditionalDocumentReference\/cbc:DocumentTypeCode\" valor: \"31\")"

**Comment by giansalex** [comment]
@guillermosg28 Hola, se actualizo el código de [ejemplo](https://github.com/thegreenter/demo/blob/685a89858a7a3cb4746a28732c60654cc59355ce/examples/factura-rel-guia-remision.php#L32), deberia incluirse en el campo:

```php
    ->setGuias([
        $guiaRemision
    ])
```

**Comment by guillermosg28** [comment]
@giansalex  muchas gracias, funciono perfecto.
