### ISSUE TITLE
Campo descuentos en Nota de Crédito

### ISSUE THREAD

**Issue by sigfrido45** [thegreenter/greenter#178]
Saludos, estoy enviando notas de crédito que tienen descuento, no obstante no se encuentra el  tag `<cbc:AllowanceTotalAmountcurrencyID="PEN">`  en el template `notacr2.1.xml.twig`.  Es de esta forma o se tiene que instanciar otra clase que no sea Note ?

**Comment by giansalex** [comment]
Hola @sigfrido45 , esa información SUNAT no la especifica en sus manuales.

**Comment by sigfrido45** [comment]
En la sección [https://cpe.sunat.gob.pe/node/88](guías) en Nota de crédito 2.1 existe el atributo total de descuentos 
![imagen](https://user-images.githubusercontent.com/33444373/122941254-d6308500-d33a-11eb-9ad6-526ddccae01d.png) me refería a ese campo.

**Comment by giansalex** [comment]
@sigfrido45 debido a la inconsistencia y desactualización de los manuales, se siguió la reglas del Excel de validación de SUNAT, que esta si recibe actualizaciones, y allí no indicaba los campos de descuentos. 
Pero en el SFS si se incluye, esto estaría pendiente para ser agregado al repositorio.

**Comment by sigfrido45** [comment]
Listo, gracias por la respuesta

**Comment by dlopez525** [comment]
Este issue es incorrecto, se deberia de revertir el cambio. Ya que una nota de credito disminuye igv por lo tanto no esta permitido los descuetos en una nota de credito. Para hacer una reduccion del costo se deberia de usar los motivos para este tipo de documento.

**Comment by giansalex** [comment]
@dlopez525 no se aplicó el cambio, cerraré este issue entonces.
