### ISSUE TITLE
Problemas al consultar ticket de resumen diario

### ISSUE THREAD

**Issue by stoner6593** [thegreenter/greenter#180]
Buen día, estoy tratando de consultar el ticket que me devuelve el envío del resumen diario pero no tengo éxito.
Lo consulto de esta manera

![image](https://user-images.githubusercontent.com/22779427/123464502-80661200-d5b2-11eb-9f94-004c246d5c0a.png)

Me retorna esto:
![image](https://user-images.githubusercontent.com/22779427/123464737-d5098d00-d5b2-11eb-90f0-637ace2e4fd0.png)

Alguna sugerencia?
También hice esto pero no funciona
https://github.com/thegreenter/demo/blob/685a89858a7a3cb4746a28732c60654cc59355ce/examples/resumen.php#L86

**Comment by guillermosg28** [comment]
Ese error es del servidor de SUNAT intenta varias veces para que te devuelva en BETA pasa eso,  me ha pasado he enviado como 15 veces para tener una respuesta correcta.

**Comment by Gildus** [comment]
De sunat los únicos servicios que funciona mal en la mayoría de casos es la consulta de los estatus tanto del CDR como del ticket. 

Te recomiendo que uses también solo para saber el estado si está o no en Sunat  con la API de consulta de CPE, esto se genera con unos ApiKeys con tu cuenta SOL.

**Comment by MrJmpl3** [comment]
Esos son problemas de SUNAT, que escapan de las validaciones de Greenter, aunque se pueden agregar gracias a los codigos de respuesta, usualmente son:

- CDR vacio
- No llega el CDR
- Ticket vacio
- Caidas de SUNAT

Como dice @Gildus se recomienda verificar usando la API SUNAT de los comprobantes.

Con Facturas no tendras muchos problemas, estos problemas son usualmente en las boletas.
