### ISSUE TITLE
Cuando falla la conexion

### ISSUE THREAD

**Issue by guillermosg28** [thegreenter/greenter#181]
Buenas noches, cuando falla la conexión de internet no me devuelve CDR pero en la pagina de la SUNAT sale como procesado pero no se puede bajar el CDR y cuando intento enviar la misma boleta me sale ERROR, el siguiente documento ha sido informado anteriormente.

<img width="1074" alt="Captura de Pantalla 2021-07-11 a la(s) 20 17 48" src="https://user-images.githubusercontent.com/6894644/125216993-46209400-e285-11eb-900e-fe4427f87d1d.png">

**Comment by MrJmpl3** [comment]
> Buenas noches, cuando falla la conexión de internet no me devuelve CDR pero en la pagina de la SUNAT sale como procesado pero no se puede bajar el CDR y cuando intento enviar la misma boleta me sale ERROR, el siguiente documento ha sido informado anteriormente.
> 
> <img alt="Captura de Pantalla 2021-07-11 a la(s) 20 17 48" width="1074" src="https://user-images.githubusercontent.com/6894644/125216993-46209400-e285-11eb-900e-fe4427f87d1d.png">

Es un error comun de parte de la SUNAT, lo que toca es que uses la consulta de la API de la SUNAT y asi verifiques si el documento ha sido informado.

**Comment by guillermosg28** [comment]
@MrJmpl3  habra algun metodo saber cuando devuelve un 98 o 99?

**Comment by MrJmpl3** [comment]
> @MrJmpl3 habra algun metodo saber cuando devuelve un 98 o 99?

El API de Consulta de SUNAT, te dice si esta informado o no

**Comment by guillermosg28** [comment]
Me referia un metodo de greenter porque si es 98 o 99 no entra al if .. if ($res->isSuccess()) {} y no termina el proceso, cuando deseo enviar de nuevo ya no se puede porque ya se informo el documento,

**Comment by giansalex** [comment]
@guillermosg28 el código `98`  cuando se consulta el estado de una c. de baja o resumen, indica que esta en proceso, y por tanto no hay CDR disponible, según la documentacion de SUNAT.
