### ISSUE TITLE
3277 - La sumatoria del total valor de venta - operaciones gravadas de línea no corresponden al total

### ISSUE THREAD

**Issue by jose1894** [thegreenter/greenter#183]
Buenas tardes, 

Muchas gracias ante todo por su apoyo,

Tengo un error al intentar pasar una nota de crédito a la SUNAT, me genera el siguiente error:

![image](https://user-images.githubusercontent.com/12040206/132256876-e71da386-a678-4bec-9468-c3e7446f19be.png)

Ya he hecho el seguimiento en el procedimiento, y he devuelto los valores para corroborar, pero aun así no logro ver que es lo que me hace falta. Comparto mi código:

Esta es la parte de la Nota:

![image](https://user-images.githubusercontent.com/12040206/132257131-1b9c13bf-e53f-4c8a-9a1b-b399ba545565.png)

Hice un var_dump y me devuelve esto:

![image](https://user-images.githubusercontent.com/12040206/132257228-6e6b783a-7e60-43d9-90c1-1f4ce0425df4.png)

Luego en la parte de los items: 

![image](https://user-images.githubusercontent.com/12040206/132257434-267a07a2-c851-4e6d-9849-3fae2e10f0a1.png)

Hice un var_dump y me devuelve esto:

![image](https://user-images.githubusercontent.com/12040206/132257480-f30176f6-f741-4ee5-9553-cd6b73d150b3.png)

Agradecido en la colaboración que puedan prestarme de antemano

**Comment by giansalex** [comment]
@jose1894 podrias compartir el archivo xml (puedes ocultar información que desees)

**Comment by jose1894** [comment]
@giansalex, no me devolvio archivo xml, adjunto la respuesta que me dio el servidor de pruebas:

C:\wamp64\www\fact\controllers\DocumentoController.php:1174:
object(Greenter\Model\Response\BillResult)[437]
  protected 'cdrZip' => null
  protected 'cdrResponse' => null
  protected 'success' => boolean false
  protected 'error' => 
    object(Greenter\Model\Response\Error)[3577]
      protected 'code' => string '3277' (length=4)
      protected 'message' => string 'La sumatoria del total valor de venta - operaciones gravadas de línea no corresponden al total - Detalle: xxx.xxx.xxx value='ticket: 1631023368419 error: INFO : 3277 (nodo: "cac:TaxSubtotal/cbc:TaxableAmount" valor: "242.52")'' (length=227)

Adjunto un error de otra nota de credito que si me devolvio xml:

![image](https://user-images.githubusercontent.com/12040206/132358866-6c5a84ca-0508-4b92-b728-41937f1330e6.png)

**Comment by giansalex** [comment]
@jose1894 puedes guardar el archivo xml que envias, 
```php
file_put_contents('ncr.xml', $see->getFactory()->getLastXml());
```

**Comment by jose1894** [comment]
@giansalex Gracias, ya puedes cerrar el caso, era un error en mi procedimiento ya lo logre depurar. 

Muchas gracias

**Comment by onixsmart** [comment]
@jose1894  Estimado Jose, como lograste solucionar, yo estoy recibiendo el mismo error 3277 al enviar una factura:

La sumatoria del total valor de venta - operaciones gravadas de línea no corresponden al total - Detalle: xxx.xxx.xxx value='ticket: 1630989666170 error: INFO : 3277 (nodo: "cac:TaxSubtotal/cbc:TaxableAmount" valor: "100.00")'

Aqui el XML de la factura:

<cac:PaymentTerms>
<cbc:ID>FormaPago</cbc:ID>
<cbc:PaymentMeansID>Contado</cbc:PaymentMeansID>
</cac:PaymentTerms>
<cac:TaxTotal>
<cbc:TaxAmount currencyID="PEN">18.00</cbc:TaxAmount>
<cac:TaxSubtotal>
<cbc:TaxableAmount currencyID="PEN">100.00</cbc:TaxableAmount>
<cbc:TaxAmount currencyID="PEN">18.00</cbc:TaxAmount>
<cac:TaxCategory>
<cac:TaxScheme>
<cbc:ID>1000</cbc:ID>
<cbc:Name>IGV</cbc:Name>
<cbc:TaxTypeCode>VAT</cbc:TaxTypeCode>
</cac:TaxScheme>
</cac:TaxCategory>
</cac:TaxSubtotal>
</cac:TaxTotal>
<cac:LegalMonetaryTotal>
<cbc:LineExtensionAmount currencyID="PEN">100.00</cbc:LineExtensionAmount>
<cbc:TaxInclusiveAmount currencyID="PEN">118.00</cbc:TaxInclusiveAmount>
<cbc:PayableAmount currencyID="PEN">118.00</cbc:PayableAmount>
</cac:LegalMonetaryTotal>
<cac:InvoiceLine>
<cbc:ID>1</cbc:ID>
<cbc:InvoicedQuantity unitCode="NIU">2</cbc:InvoicedQuantity>
<cbc:LineExtensionAmount currencyID="PEN">100.00</cbc:LineExtensionAmount>
<cac:PricingReference>
<cac:AlternativeConditionPrice>
<cbc:PriceAmount currencyID="PEN">59</cbc:PriceAmount>
<cbc:PriceTypeCode>01</cbc:PriceTypeCode>
</cac:AlternativeConditionPrice>
</cac:PricingReference>
<cac:TaxTotal>
<cbc:TaxAmount currencyID="PEN">18.00</cbc:TaxAmount>
<cac:TaxSubtotal>
<cbc:TaxableAmount currencyID="PEN">100.00</cbc:TaxableAmount>
<cbc:TaxAmount currencyID="PEN">18.00</cbc:TaxAmount>
<cac:TaxCategory>
<cbc:Percent>18</cbc:Percent>
<cbc:TaxExemptionReasonCode>10</cbc:TaxExemptionReasonCode>
<cac:TaxScheme>
<cbc:ID>1000</cbc:ID>
<cbc:Name>IGV</cbc:Name>
<cbc:TaxTypeCode>VAT</cbc:TaxTypeCode>
</cac:TaxScheme>
</cac:TaxCategory>
</cac:TaxSubtotal>
</cac:TaxTotal>
<cac:Item>
<cbc:Description>
<![CDATA[ Abrazadera cerrada de bronce 3/8 ]]>
</cbc:Description>
</cac:Item>
<cac:Price>
<cbc:PriceAmount currencyID="PEN">50</cbc:PriceAmount>
</cac:Price>
</cac:InvoiceLine>
<cac:InvoiceLine>
<cbc:ID>2</cbc:ID>
<cbc:InvoicedQuantity unitCode="NIU">2</cbc:InvoicedQuantity>
<cbc:LineExtensionAmount currencyID="PEN">100.00</cbc:LineExtensionAmount>
<cac:PricingReference>
<cac:AlternativeConditionPrice>
<cbc:PriceAmount currencyID="PEN">59</cbc:PriceAmount>
<cbc:PriceTypeCode>01</cbc:PriceTypeCode>
</cac:AlternativeConditionPrice>
</cac:PricingReference>
<cac:TaxTotal>
<cbc:TaxAmount currencyID="PEN">18.00</cbc:TaxAmount>
<cac:TaxSubtotal>
<cbc:TaxableAmount currencyID="PEN">100.00</cbc:TaxableAmount>
<cbc:TaxAmount currencyID="PEN">18.00</cbc:TaxAmount>
<cac:TaxCategory>
<cbc:Percent>18</cbc:Percent>
<cbc:TaxExemptionReasonCode>10</cbc:TaxExemptionReasonCode>
<cac:TaxScheme>
<cbc:ID>1000</cbc:ID>
<cbc:Name>IGV</cbc:Name>
<cbc:TaxTypeCode>VAT</cbc:TaxTypeCode>
</cac:TaxScheme>
</cac:TaxCategory>
</cac:TaxSubtotal>
</cac:TaxTotal>
<cac:Item>
<cbc:Description>
<![CDATA[ Abrazadera cerrada de bronce 3/8 ]]>
</cbc:Description>
</cac:Item>
<cac:Price>
<cbc:PriceAmount currencyID="PEN">50</cbc:PriceAmount>
</cac:Price>
</cac:InvoiceLine>
</Invoice>

**Comment by jose1894** [comment]
@onixsmart Puedo decirte que mi error estaba en que  yo  en la Nota declaraba un valor y el ciclo donde se agregan los items a la nota agregaba una iteracion mas, por lo tanto no concordaba lo que recibia la Nota con los items que procesaba en el ciclo. 

Tuve que depurar el procedimiento completo, alli fue cuando me funciono

**Comment by onixsmart** [comment]
He depurado mi procedimiento de pies a cabeza y no encuentro nada irregular.  Incluso el xml lo veo correcto. Me sigue saliendo el error 3722. Me estoy deprimiendo
