### ISSUE TITLE
error: INFO : 3277 - La sumatoria del total valor de venta - operaciones gravadas de línea no corresponden al total

### ISSUE THREAD

**Issue by onixsmart** [thegreenter/greenter#184]
Desde que actualice de la version 4.0 a 4.3, para actualizar la "formadepago:contado" estoy recibiendo el error 3277 al enviar una factura:

La sumatoria del total valor de venta - operaciones gravadas de línea no corresponden al total - Detalle: xxx.xxx.xxx value='ticket: 1630989666170 error: INFO : 3277 (nodo: "cac:TaxSubtotal/cbc:TaxableAmount" valor: "100.00")'

Este es el XML de la factura:
Muchas gracias espero lo puedan ver y ayudarme

cac:PaymentTerms
cbc:IDFormaPago</cbc:ID>
cbc:PaymentMeansIDContado</cbc:PaymentMeansID>
</cac:PaymentTerms>
cac:TaxTotal
<cbc:TaxAmount currencyID="PEN">18.00</cbc:TaxAmount>
cac:TaxSubtotal
<cbc:TaxableAmount currencyID="PEN">100.00</cbc:TaxableAmount>
<cbc:TaxAmount currencyID="PEN">18.00</cbc:TaxAmount>
cac:TaxCategory
cac:TaxScheme
cbc:ID1000</cbc:ID>
cbc:NameIGV</cbc:Name>
cbc:TaxTypeCodeVAT</cbc:TaxTypeCode>
</cac:TaxScheme>
</cac:TaxCategory>
</cac:TaxSubtotal>
</cac:TaxTotal>
cac:LegalMonetaryTotal
<cbc:LineExtensionAmount currencyID="PEN">100.00</cbc:LineExtensionAmount>
<cbc:TaxInclusiveAmount currencyID="PEN">118.00</cbc:TaxInclusiveAmount>
<cbc:PayableAmount currencyID="PEN">118.00</cbc:PayableAmount>
</cac:LegalMonetaryTotal>
cac:InvoiceLine
cbc:ID1</cbc:ID>
<cbc:InvoicedQuantity unitCode="NIU">2</cbc:InvoicedQuantity>
<cbc:LineExtensionAmount currencyID="PEN">100.00</cbc:LineExtensionAmount>
cac:PricingReference
cac:AlternativeConditionPrice
<cbc:PriceAmount currencyID="PEN">59</cbc:PriceAmount>
cbc:PriceTypeCode01</cbc:PriceTypeCode>
</cac:AlternativeConditionPrice>
</cac:PricingReference>
cac:TaxTotal
<cbc:TaxAmount currencyID="PEN">18.00</cbc:TaxAmount>
cac:TaxSubtotal
<cbc:TaxableAmount currencyID="PEN">100.00</cbc:TaxableAmount>
<cbc:TaxAmount currencyID="PEN">18.00</cbc:TaxAmount>
cac:TaxCategory
cbc:Percent18</cbc:Percent>
cbc:TaxExemptionReasonCode10</cbc:TaxExemptionReasonCode>
cac:TaxScheme
cbc:ID1000</cbc:ID>
cbc:NameIGV</cbc:Name>
cbc:TaxTypeCodeVAT</cbc:TaxTypeCode>
</cac:TaxScheme>
</cac:TaxCategory>
</cac:TaxSubtotal>
</cac:TaxTotal>
cac:Item
cbc:Description

</cbc:Description>
</cac:Item>
cac:Price
<cbc:PriceAmount currencyID="PEN">50</cbc:PriceAmount>
</cac:Price>
</cac:InvoiceLine>
cac:InvoiceLine
cbc:ID2</cbc:ID>
<cbc:InvoicedQuantity unitCode="NIU">2</cbc:InvoicedQuantity>
<cbc:LineExtensionAmount currencyID="PEN">100.00</cbc:LineExtensionAmount>
cac:PricingReference
cac:AlternativeConditionPrice
<cbc:PriceAmount currencyID="PEN">59</cbc:PriceAmount>
cbc:PriceTypeCode01</cbc:PriceTypeCode>
</cac:AlternativeConditionPrice>
</cac:PricingReference>
cac:TaxTotal
<cbc:TaxAmount currencyID="PEN">18.00</cbc:TaxAmount>
cac:TaxSubtotal
<cbc:TaxableAmount currencyID="PEN">100.00</cbc:TaxableAmount>
<cbc:TaxAmount currencyID="PEN">18.00</cbc:TaxAmount>
cac:TaxCategory
cbc:Percent18</cbc:Percent>
cbc:TaxExemptionReasonCode10</cbc:TaxExemptionReasonCode>
cac:TaxScheme
cbc:ID1000</cbc:ID>
cbc:NameIGV</cbc:Name>
cbc:TaxTypeCodeVAT</cbc:TaxTypeCode>
</cac:TaxScheme>
</cac:TaxCategory>
</cac:TaxSubtotal>
</cac:TaxTotal>
cac:Item
cbc:Description

</cbc:Description>
</cac:Item>
cac:Price
<cbc:PriceAmount currencyID="PEN">50</cbc:PriceAmount>
</cac:Price>
</cac:InvoiceLine>

**Comment by giansalex** [comment]
@onixsmart el problema no tiene que ver con la actualización de la versión, he visto varias publicaciones desde inicios de setiembre por problemas de precisión en los cálculos que ahora SUNAT no acepta.
Aunque en el caso que presentas, se ve tienes 2 items de 100, pero en los total de cabecera solo aparece 100, en vez de 200.

**Comment by onixsmart** [comment]
![image](https://user-images.githubusercontent.com/47246020/133097346-577e4401-518e-4ee6-8324-835bce787ca5.png)

**Comment by onixsmart** [comment]
Muchas gracias, equivocadamente pensé que asi era la estructura del xml.
