### ISSUE TITLE
Descuentos globales y Total cargo

### ISSUE THREAD

**Issue by yahyrparedes** [thegreenter/greenter#186]
Estoy trabajando con Efact y uso greenter para generar mis comprobantes, tuve un caso atípico con el ubl 2.0, se que está en desuso y no se debería usar.

Pero el sistema es legasy, y como para no romper casi nada lo que se hice fue lo sgt.

Agregar unas validaciones en twig a esos campo, para evitar que se agreguen de manera automática aún sin que lo indiquemos. 
Cómo son datos de tipo flotante siempre se imprime 0.00.

Adjunto código de error:
<cbc:AllowanceTotalAmount currencyID="PEN">0.00</cbc:AllowanceTotalAmount>
<cbc:ChargeTotalAmount currencyID="PEN">0.00</cbc:ChargeTotalAmount>
Error (2968): Debe contener un importe mayor a 0.00 si envía el tag cac:AllowanceCharge/cbc:Amount cbc:Amount: 0.00

Adjunto respuesta de solución:
{% if doc.sumDsctoGlobal != 0.00 %}
        <cbc:AllowanceTotalAmount currencyID="{{ doc.tipoMoneda }}">{{ doc.sumDsctoGlobal|default(0)|n_format }}</cbc:AllowanceTotalAmount>
        {% endif %}
        {% if doc.mtoOtrosTributos != 0.00 %}
        <cbc:ChargeTotalAmount currencyID="{{ doc.tipoMoneda }}">{{ doc.mtoOtrosTributos|default(0)|n_format }}</cbc:ChargeTotalAmount>
        {% endif %}

Creare un branch y PR para la librería. 

Espero ayude a los que tengan este problema.

**Comment by giansalex** [comment]
@yahyrparedes en que casos SUNAT acepta facturas en UBL 2.0?

**Comment by PercyWoeds** [comment]
Sunat ya no acepta 2.0 esta con el ubl 2.1
