### ISSUE TITLE
facturas con retencion

### ISSUE THREAD

**Issue by PercyWoeds** [thegreenter/greenter#188]
Hola 

Una consulta si una empresa realiza una factura al credito a una empresa retenedora , y en el importe de cuota tendria que descontar esta retencion, cual es el codigo para indicar que el descuento es por una retencion  en el xml .

Gracias de antemano

**Comment by dlopez525** [comment]
No hay código para eso, podrias restar en el monto pendiente de pago la retencion. La empresa "retenedora" deberia de emitirte un comprobante de retención.
