### ISSUE TITLE
Nota de credito al contado

### ISSUE THREAD

**Issue by guillermosg28** [thegreenter/greenter#191]
Buenas noches cuando realizo una nota de crédito al contado me sale este error.
"sunat_code": "3246",
"sunat_message": "El tipo de transaccion o el identificador de la cuota no cumple con el formato esperado - Detalle: xxx.xxx.xxx value='ticket: 1634614171354 error: INFO: 3246 (nodo: "cac:PaymentTerms/cbc:PaymentMeansID" valor: "Contado")'"
}

**Comment by p3dr0tg** [comment]
solo se envia forma de pago cuando es tipo nota de credito 13
