### ISSUE TITLE
CERTIFICADO DIGITAL SUNAT - CDT

### ISSUE THREAD

**Issue by marcuspc** [thegreenter/greenter#193]
Estimado @giansalex buenas tardes, quería consultarte acerca de los certificados digitales que actualmente esta dando SUNAT gratuitamente, también se debe generar un usuario secundario para usarlo en la emisión de los comprobante electrónicos?

**Comment by erajuan** [comment]
@marcuspc para emitir comprobantes electronicos necesitas:
- Certificado Digital (Entregado por sunat / comprar proveedo privado)
- Usuario Secundario - SOL
