### ISSUE TITLE
Modelos sin un toString o un toJson ?

### ISSUE THREAD

**Issue by erickAvSanti** [thegreenter/greenter#194]
Es dificil debugear los modelos desde php artisan tinker cuando se tiene un proyecto grande... No tiene sentido puros setXXX, getXXX cuando practicamente se tiene variables privadas sin sentido cuando tranquilamente se puede hacer público e imprimirlo con un json_encode($client).

**Comment by giansalex** [comment]
Es un patrón relacionado con Symfony, pero es posible implementar `JsonSerializable` y sea compatible con json_encode
