### ISSUE TITLE
ActionNotSupported-The message with Action 'sendBill'

### ISSUE THREAD

**Issue by mfrankm1125** [thegreenter/greenter#196]
Buen día a todos, tengo este problema desde el 30/06/2022   alguien sabe como solucionarlo.
 
![error endpoint](https://user-images.githubusercontent.com/7536256/176916548-3818bb59-078b-4f81-9b4e-9a05230be3bd.png)

**Comment by giansalex** [comment]
Estas enviando a una OSE?

**Comment by mfrankm1125** [comment]
No envió a OSE, también se genera el  error HTTP-Bad Gatway ,

**Comment by giansalex** [comment]
@francisivan1 `Bad Gatway` ha sido un problema conocido en los servicios de SUNAT, tal vez sea algo temporal.
Revisaré si encuentro algo.

**Comment by FranciscoOrrego** [comment]
> Buen día a todos, tengo este problema desde el 30/06/2022 alguien sabe como solucionarlo.
> 
> ![error endpoint](https://user-images.githubusercontent.com/7536256/176916548-3818bb59-078b-4f81-9b4e-9a05230be3bd.png)

tenemos este error, sigo investigando pero parece  por el lado de SSL  de SUNAT ? . alguien tiene una idea  mas

**Comment by FranciscoOrrego** [comment]
@giansalex  hubo alguna   novedad  , alguna luz..  no puedo  encontrar una solucion . Gracias por tu apoyo

**Comment by giansalex** [comment]
Parece que es un problema con los servicios de SUNAT, otros usuarios indican que tuvieron ese problema y otros no, pero que ya se solucionó.
