### ISSUE TITLE
Emisión de Boletas Electrónicas en Nuevo Régimen Único Simplificado (NRUS)

### ISSUE THREAD

**Issue by willyk** [thegreenter/greenter#198]
Estimados,

Alguno tendrá un ejemplo de emisión de Boletas Electrónicas para RUCs del Nuevo Régimen Único Simplificado (NRUS)?

Se asume que estas NO son Exonerados, Inafecto o de Exportación según el catalogo 07 de la Sunat.

A continuación envío como ejemplo el caso y lo que hemos avanzando.

Caso de emisión de boletas del RUC que se encuentra en el régimen NRUS, actualmente está emitiendo por el portal Sunat con clave SOL, adjuntamos el XML de una boleta real emitida por el portal donde está todo correcto, el nombre del archivo adjunto es "XML con clave SOL BOLETAE B01-14-10703516XXX.XML" esto como ejemplo de lo que deseamos lograr.

En nuestro caso el RUC ya está dado de alta en una OSE, hemos emitido una primera boleta en ambiente de producción y nos devuelve un error:
3111: El monto de afectaci\u00f3n de IGV por línea debe ser diferente a 0.00.
El nombre del archivo adjunto es "R-10703516XXX-03-B001-00000001-REQUEST.XML" hemos conversado con Informática de Sunat y validado y todo está OK, solicitamos apoyo para lograr la emisión correcta a la OSE, teniendo las consideraciones del régimen NRUS y nos responden con las validaciones aplicadas y que en todo caso veamos con un contador.

Comentar que hemos agregado en el XML generado un comentario como sigue para poder entender mas a detalle:

Por favor solicitamos alguna orientación o apoyo ya que hemos llegado al punto de estar en un ping pong entre la Sunat y la OSE, y no tenemos idea de cuál de ellos tienen razón.

Agradecidos por sus comentarios, gracias.

Adjunto ZIP con los 2 XMLs
[Caso Boleta E NRUS.zip](https://github.com/thegreenter/greenter/files/9075864/Caso.Boleta.E.NRUS.zip)

**Comment by giansalex** [comment]
Algo que veo en la boleta de SUNAT, es que usa el tipo de operacion: `0101` (venta interna), en vez de 0113 
`<cbc:InvoiceTypeCode listID="0101" ..>03</cbc:InvoiceTypeCode>`

**Comment by willyk** [comment]
@giansalex gracias por tu comentario, en un principio nuestras pruebas fueron así
<cbc:InvoiceTypeCode listID="0101" >03</cbc:InvoiceTypeCode>

Luego llamamos a Sunat y para que no salga el error 3111 nos indicaron usar
<cbc:InvoiceTypeCode listID="0113" >03</cbc:InvoiceTypeCode>

Pero a pesar de eso no encontramos solución, alguna idea en donde consultar? o alguna pista que nos ayude con la posible solución, estamos entrampados con la Sunat

**Comment by willyk** [comment]
Hola @Jhamnerx vi un issue tuyo acerca de NRUS, alguna idea de este caso? gracias por anticipado.

**Comment by Jhamnerx** [comment]
> Hola @Jhamnerx vi un issue tuyo acerca de NRUS, alguna idea de este caso? gracias por anticipado.
Hola, yo las envio aun con 0101 pero intentare con 0113 a ver si tengo el mismo error.

**Comment by Jhamnerx** [comment]
Veo que tu error es que caudno el TaxAmount  era 00.00 no se enviaba el taxsubtal #239 revisa este pull ya lo soluciona
