### ISSUE TITLE
Guías de remisión para el nuevo sistema de recepción

### ISSUE THREAD

**Issue by OscarERH** [thegreenter/greenter#205]

**Comment by malc32** [comment]
parece que ahora se tiene que enviar a una direccion 
https://api-cpe.sunat.gob.pe/v1/contribuyente/gem/comprobantes/{numRucEmisor}-{codCpe}-{numSerie}-{numCpe}
es una api rest

**Comment by Recursero** [comment]
Atento a los nuevos cambios.
Gracias!

**Comment by malc32** [comment]
Hola giansalex, he podido obtener el token usado para enviar el rest api, el problema es que siempre me arroja error 500 , envio el archivo y el base64 y el hash y nada, haz logrado evitar el error 500?

**Comment by giansalex** [comment]
Mi prioridad ahora mismo es agregar los campos nuevos para el xml, no he probado el API, pero he visto que varios en el chat de Telegram han podido hacerlo.

**Comment by lecano** [comment]
Yo estaba viviendo debajo de una piedra y no sabia de esta actualización.

Obtener el token y enviar el archivo por api funciona luego de algunos intentos gracias a la mala documentación de SUNAT.

Por el momento yo recibo el siguiente error:

Envío con error 2112 CustomizationID - La version del documento no es correcta : error: INFO: errorCode 2112 (nodo: "DespatchAdvice/cbc:CustomizationID" valor: "1.0")

Según el archivo ValidaExprRegGreRemitente-2.0.1.xsl ahora se requiere poner 2.0 o superior en el siguiente campo:

https://github.com/thegreenter/greenter/blob/master/packages/xml/src/Xml/Templates/despatch.xml.twig#L10

**Comment by giansalex** [comment]
Actualizar a la versión `^5.0` de los paquetes en su `composer.json`, luego ejecutar
```
composer update "greenter/*" --with-all-dependencies
```

**Comment by jcachi** [comment]
Hola estoy haciendo aun algunas pruebas para definir mi proyecto de Guias de Remision e hice una representacion impresa y en el formato de GRE remitente no salen los datos del vehiculo o del chofer ... eso lo definiran o la modificacion del twig va por cuenta propia ... Saludos

**Comment by giansalex** [comment]
@jcachi es complicado hacer un PDF que cumpla con los requerimientos de cada empresa, podrian mantener sus mismos diseños  o modificar la representacion base de este repo.

**Comment by jcachi** [comment]
Gracias Giancarlos si claro hacer un formato para cada empresa seria de locos . Hice una revision del twig del xml y si estaban los datos de chofer y vehiculo para el caso de GRE remitente y en base a ello los agrege al twig del pdf . 
Saludos 


De: "Giancarlos Salas" ***@***.***> 
Para: "thegreenter/greenter" ***@***.***> 
CC: "jcachi" ***@***.***>, "Mention" ***@***.***> 
Enviados: Miércoles, 3 de Mayo 2023 19:18:24 
Asunto: Re: [thegreenter/greenter] Guías de remisión para el nuevo sistema de recepción (Issue #205) 





[ https://github.com/jcachi | @jcachi ] es complicado hacer un PDF que cumpla con los requerimientos de cada empresa, podrian mantener sus mismos diseños o modificar la representacion base de este repo.
