### ISSUE TITLE
Retorno de token

### ISSUE THREAD

**Issue by lcarbajals** [thegreenter/greenter#219]
### Al generar el token, usando la funcion getToken(), del archivo greenter/ws/src/Api/ApiFactory.php, con el postman retorna el mensaje del cliente no autorizado, tal como se muestra:
![image](https://user-images.githubusercontent.com/113356946/216987930-f0f55849-d0d6-429b-957f-71c0c1b2e195.png)
### Pero al usar la funcion, no valida el $result:
private function getToken(?string $clientId, ?string $secret, ?string $user, ?string $password): ?string
    {
        $tokenData = $this->store->get($clientId);
        if ($tokenData && $tokenData->getExpire() > $this->addSeconds(new DateTime(), 600)) {
            return $tokenData->getValue();
        }
        $result = $this->api->getToken(
            'password',
            'https://api-cpe.sunat.gob.pe',
            $clientId,
            $secret,
            $user,
            $password
        );
       _//**Faltaria:**_
       //_**Validar si cliente está autorizado**_ 
          `//**throw` new Exception('Cliente No autorizado');**
      //_**Validar si resultado es vacio**_
          `//**throw` new Exception('No se pudo obtener el token, intente en unos inutos');**
        $token = $result->getAccessToken();
        $expire =  $this->addSeconds(new DateTime(), $result->getExpiresIn());
        $this->store->set($clientId, new BasicToken($token, $expire));

        return $token;
    }

### Ya que no valida ninguna de las opciones mencionadas, genera el siguiente error
![image](https://user-images.githubusercontent.com/113356946/216988962-193271b2-820b-4eef-bdc9-b8799102b5b5.png)
ya que intenta asignar un tiempo de expiracion en la linea:
$this->addSeconds(new DateTime(), $result->getExpiresIn());

**Comment by giansalex** [comment]
Has revisado que _HTTP code_ devuelve en Postamn? tal vez esta retornando 200 OK

**Comment by lcarbajals** [comment]
Cuando el cliente no está autorizado, retorna así el postman, pero el algoritmo en la funcion getToken, deja pasar porque no hay una validación si $result tiene valor o no 
![image](https://user-images.githubusercontent.com/113356946/217954825-50559c9f-fa1a-4d7c-ac54-a5163cab3254.png)

**Comment by giansalex** [comment]
Deberia retornar una excepcion cuando el http code es 401, el problema debe estar en el generador de API.

De cualquier forma validar el _result_, sera la solucion mas rapida
