### ISSUE TITLE
setAtributos

### ISSUE THREAD

**Issue by guillermosg28** [thegreenter/greenter#225]
Buenas, en la ultima versión no esta el ->setAtributos() para incluir placa de vehiculo en una factura (Venta de gasolina).

Saludos.

**Comment by giansalex** [comment]
Hola, ese campo no se ha quitado, prueba volviendo a instalar

**Comment by guillermosg28** [comment]
Acabo de instalar de nuevo "greenter/greenter": "^5.0", y no se encuentra en Model\Sale\Invoice

**Comment by giansalex** [comment]
puedes intentar instalando `"greenter/lite": "^5.0"`

**Comment by guillermosg28** [comment]
igual no aparece la función setAtributos

**Comment by guillermosg28** [comment]
acabo de verificar y el setAtributos esta en SaleDetail, no deberia ir en Invoice ?

Saludos.

**Comment by giansalex** [comment]
@guillermosg28 debe estar en los detalles
