### ISSUE TITLE
Redondeo a dos decimales con error: cantidad, mtoValorUnitario y mtoPrecioUnitario

### ISSUE THREAD

**Issue by Recursero** [thegreenter/greenter#230]
Hola Giancarlos:

Hoy registré un bug al enviar una factura con el valor unitario que tiene 3 decimales. En mi función los valores unitarios y la cantidad acepta has 10 decimales. Me he percatado en cuando se firma el documento, la librería lo redondea a dos decimales y ahí sucede el error: 
"3271 - El valor de venta por ítem difiere de los importes consignados..."
Para que pruebes lo que te informo emite un comprobante con cantidad 700 y precio unitario 1.102

he generado mas de 20 facturas y recién me percato que es el XML que se genera el que redondea a dos decimales.
![image](https://github.com/thegreenter/greenter/assets/45543343/06e99196-aabe-4670-a08d-316a352b5139)

No se como podría arreglar este bug.

De antemano, muchas gracias por tu gran librería que ayuda a mucho compatriotas.

**Comment by giansalex** [comment]
@Recursero gracias por informar ese dato.

**Comment by Recursero** [comment]
Actualmente el template invoice2.1.xml.twig está de esta forma {{ cuota.monto|n_format }}
la correción sería el cambio a {{ cuota.monto|n_format_limit(2)}}

Realmente hay campos, sobre todo en campos numéricos que Sunat está respondiendo con error sí no cumplen con el formato de sus validaciones.

Lo curioso de todo esto es que mi función envía los decimales (mínimos y máximos) que permite Sunat.
Esto me hace deducir que es la conversión al template que genera estos cambios (redondeo de decimales).
La solución global sería limitar la cantidad máxima de los importes según las validaciones que generen error en Sunat.
{{ variableNumérica|n_format_limit(maxPermitidoSunat)}}

Saludos @giansalex y nuevamente gracias.

**Comment by giansalex** [comment]
@Recursero `n_format` por defecto limita a 2 decimales, siempre debería aparecer con 2 decimales en el XML, o te aparecen mas decimales a ti?

**Comment by Recursero** [comment]
> @Recursero `n_format` por defecto limita a 2 decimales, siempre debería aparecer con 2 decimales en el XML, o te aparecen mas decimales a ti?

Sí, aparece con varios decimales.
![image](https://github.com/thegreenter/greenter/assets/45543343/386f3c97-a3fc-4c58-989d-4bd5fa57a74d)

**Comment by giansalex** [comment]
@Recursero se habia realizado el cambio, pero no esta incluida en ninguna version.
Fue incluido en la v5.0.1, puedes actualizar greenter

**Comment by Recursero** [comment]
Perfecto!
Ahora lo actualizo.
Gracias.

**Comment by Recursero** [comment]
Hola Giancarlos:

Estoy haciendo pruebas en producción y el error persiste en el redondeo. A pesar de que yo le envío solo dos decimales en el importe de la cuota (1.15) el XML se firma y envía a Sunat con 1.149999999999999911182.
Será posible que trunques ese importe a dos decimales para que twig no lo redondee.
![image](https://github.com/thegreenter/greenter/assets/45543343/79a381b5-de2a-446b-bed6-136007a4d51b)

**Comment by giansalex** [comment]
Es raro que salga con esos decimales adicionales, tal vez es alguna configuración en php
![image](https://github.com/thegreenter/greenter/assets/14926587/ac8e246d-10fe-459b-b63b-69508efb1df6)

De todas formas falto agregar el filtro de formato al total de cuotas

**Comment by giansalex** [comment]
@Recursero se agrego al campo que faltaba, en la v5.0.2

**Comment by Recursero** [comment]
> @Recursero se agrego al campo que faltaba, en la v5.0.2

Gracias Giancarlos.
