### ISSUE TITLE
timeOut en respuesta de Sunat

### ISSUE THREAD

**Issue by Recursero** [thegreenter/greenter#235]
Hola Giancarlos:
Existe una forma de descartar la respuesta del método send(), porque a veces la Sunat puede tardar más de 1 minuto y ahí se dispara el max_execution_time de PHP.
Gracias de antemano por tu respuesta

EDIT: Usar max_execution_time

**Comment by giansalex** [comment]
existe un parametro en `SoapClient`  que se usa internamente
```php
$client = new SOAPClient($wsdl, array('connection_timeout' => 1));
```
