### ISSUE TITLE
Emisión de notas de crédito por anulación de operación para facturas o boletas con descuento

### ISSUE THREAD

**Issue by AnthonyLJ96** [thegreenter/greenter#237]
Hola @giansalex cómo se debe manejar los casos en los que se quiere anular una boleta o factura con nota de crédito en los cuales estos comprobantes han tenido un descuento global?.

**Comment by giansalex** [comment]
Estas preguntas puedes hacerla en el grupo de Telegram https://t.me/thegreenter , y si se necesita agregar o modificar el codigo, se crea un _issue_

**Comment by obed888** [comment]
Buen dia @giansalex  mira tengo este caso de una factura con descuento global que cuando quiero hacer la nota de credito me sale error porque el xml no registra la etiqueta AllowanceTotalAmont con el monto del descuento, sera que se puede reabrir este caso?
Vi en telegram que tenia que descontar el monto o prorratear el monto en los items pero realmente se tiene que agregar esa etiqueta segun documentacion, ya escribi al telegram y tampoco tengo respuesta.
`
	<cac:LegalMonetaryTotal>
		<cbc:LineExtensionAmount currencyID="PEN">15.00</cbc:LineExtensionAmount>
				<cbc:AllowanceTotalAmount currencyID="PEN">5.00</cbc:AllowanceTotalAmount> 
		<cbc:ChargeTotalAmount currencyID="PEN">0.00</cbc:ChargeTotalAmount>
		  		  <cbc:PrepaidAmount currencyID="PEN">0.00</cbc:PrepaidAmount>
		  		        
        		<cbc:PayableAmount currencyID="PEN">17.70</cbc:PayableAmount>
	</cac:LegalMonetaryTotal>`

**Comment by giansalex** [comment]
@obed888 si existe esa etiqueta en el xml, esta en el campo de invoice como `sumOtrosDescuento`

**Comment by obed888** [comment]
@giansalex pero me refiero que ese campo no existe en la clase Note() solo existe para el Invoice(), el xml que te adjunte es de una nota de credito con descuento global

**Comment by giansalex** [comment]
@obed888 he revisado las especificaciones en nota de credito, y no se encuentra ese campo, asi lo incluyera, sunat no lo validaría. 
Puedes encontrar los campos que sunat valida en el primer enlace de [reglas de validacion](https://cpe.sunat.gob.pe/guias-y-manuales)

**Comment by obed888** [comment]
Gracias @giansalex  es correcto adjunto el punto donde detalla esta informacion:
4 Descuento global. Motivo a utilizarse cuando se aplique descuentos a los importes totales
de una factura electrónica. **No se permite la emisión de notas de crédito por descuentos
globales** tratándose de operaciones con consumidores finales, es decir descuentos sobre
boletas de ventaelectrónica.
